http:
  host: localhost
  port: 8080
postgresql:
  user:
  password:
  host:
  port:
  database: estate_service
  ssl_mode:
  auto_create:
auth_api:
  url:
jwt:
  sign_key: secret # provide as env var
  token_ttl: 60m

