# todo dont expose posgtresql portt
services:

  postgres:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
      POSTGRES_DB: "estate_service"
    volumes:
      - ./app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  service:
#    container_name: service
#    build:
#      context: .
#    restart: always
#    environment:
#      - PG_HOST=postgres
#    volumes:
#      - ./data://usr/local/bin/data
#      - ./config.yaml:/usr/local/bin/config.yaml
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres