definitions:
  github_com_romanchechyotkin_avito_test_task_internal_controller_v1_request.CreateFlat:
    properties:
      house_id:
        type: integer
      number:
        type: integer
      price:
        type: integer
      rooms_amount:
        type: integer
    required:
    - house_id
    - number
    - price
    - rooms_amount
    type: object
  github_com_romanchechyotkin_avito_test_task_internal_controller_v1_request.CreateHouse:
    properties:
      address:
        type: string
      developer:
        type: string
      year:
        type: integer
    required:
    - address
    - year
    type: object
  github_com_romanchechyotkin_avito_test_task_internal_controller_v1_request.Login:
    properties:
      email:
        type: string
      password:
        maxLength: 50
        minLength: 4
        type: string
    type: object
  github_com_romanchechyotkin_avito_test_task_internal_controller_v1_request.Registration:
    properties:
      email:
        type: string
      password:
        maxLength: 50
        minLength: 4
        type: string
      user_type:
        enum:
        - client
        - moderator
        type: string
    type: object
  github_com_romanchechyotkin_avito_test_task_internal_controller_v1_request.UpdateFlat:
    properties:
      id:
        type: integer
      status:
        enum:
        - created
        - approved
        - declined
        - on moderation
        type: string
    required:
    - id
    - status
    type: object
  github_com_romanchechyotkin_avito_test_task_internal_controller_v1_response.Flat:
    properties:
      created_at:
        type: string
      house_id:
        type: integer
      id:
        type: integer
      moderation_status:
        type: string
      number:
        type: integer
      price:
        type: integer
      rooms_amount:
        type: integer
      updated_at:
        type: string
    type: object
  github_com_romanchechyotkin_avito_test_task_internal_controller_v1_response.House:
    properties:
      address:
        type: string
      created_at:
        type: string
      developer:
        type: string
      id:
        type: integer
      updated_ats:
        type: string
      year:
        type: integer
    type: object
  github_com_romanchechyotkin_avito_test_task_internal_controller_v1_response.HouseFlats:
    properties:
      flats:
        items:
          $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_entity.Flat'
        type: array
    type: object
  github_com_romanchechyotkin_avito_test_task_internal_controller_v1_response.Login:
    properties:
      token:
        type: string
    type: object
  github_com_romanchechyotkin_avito_test_task_internal_controller_v1_response.Registration:
    properties:
      user_id:
        type: string
    type: object
  github_com_romanchechyotkin_avito_test_task_internal_entity.Flat:
    properties:
      createdAt:
        type: string
      houseID:
        type: integer
      id:
        type: integer
      moderationStatus:
        type: string
      number:
        type: integer
      price:
        type: integer
      roomsAmount:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_controller_v1_request.Login'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_controller_v1_response.Login'
      summary: Login
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registration
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_controller_v1_request.Registration'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_controller_v1_response.Registration'
      summary: Registration
      tags:
      - auth
  /v1/flat/create:
    post:
      consumes:
      - application/json
      description: Create Flat
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_controller_v1_request.CreateFlat'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_controller_v1_response.Flat'
      security:
      - JWT: []
      summary: Create Flat
      tags:
      - flat
  /v1/flat/update:
    post:
      consumes:
      - application/json
      description: Update Flat
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_controller_v1_request.UpdateFlat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_controller_v1_response.Flat'
      security:
      - JWT: []
      summary: Update Flat
      tags:
      - flat
  /v1/house/{id}:
    get:
      consumes:
      - application/json
      description: Get House Flats
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_controller_v1_response.HouseFlats'
      security:
      - JWT: []
      summary: Get House Flats
      tags:
      - house
  /v1/house/{id}/subscribe:
    post:
      consumes:
      - application/json
      description: Subscribe for house updates
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - JWT: []
      summary: Subscribe for house updates
      tags:
      - house
  /v1/house/create:
    post:
      consumes:
      - application/json
      description: Create House
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_controller_v1_request.CreateHouse'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_romanchechyotkin_avito_test_task_internal_controller_v1_response.House'
      security:
      - JWT: []
      summary: Create House
      tags:
      - house
swagger: "2.0"
